#Author:

TOP=../..
include $(TOP)/configure/CONFIG

#add macros here

#optimization of db files using dbst(DEFAULT:NO)
#DB_OPT=YES

DB += NDFileArrow.template
DB += NDFileArrow_settings.req

include $(TOP)/configure/RULES

#add rules here
