TOP=..
include $(TOP)/configure/CONFIG


LIB_INSTALLS_Linux += ../os/linux-x86_64/libarrow.a
LIB_INSTALLS_Linux += ../os/linux-x86_64/libarrow.so
LIB_INSTALLS_Linux += ../os/linux-x86_64/libarrow_bundled_dependencies.a

include $(TOP)/configure/RULES
